# =============================================================================
# GitHub Labels Configuration
# Use with: https://github.com/EndBug/label-sync
# =============================================================================

# -----------------------------------------------------------------------------
# Type Labels
# -----------------------------------------------------------------------------
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "type: feature"
  color: "a2eeef"
  description: "New feature or request"

- name: "type: enhancement"
  color: "84b6eb"
  description: "Improvement to existing feature"

- name: "type: documentation"
  color: "0075ca"
  description: "Documentation updates"

- name: "type: refactor"
  color: "fbca04"
  description: "Code refactoring"

- name: "type: test"
  color: "bfd4f2"
  description: "Test-related changes"

- name: "type: chore"
  color: "fef2c0"
  description: "Maintenance tasks"

- name: "type: security"
  color: "d93f0b"
  description: "Security-related issues"

# -----------------------------------------------------------------------------
# Priority Labels
# -----------------------------------------------------------------------------
- name: "priority: critical"
  color: "b60205"
  description: "Must be fixed immediately"

- name: "priority: high"
  color: "d93f0b"
  description: "High priority"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority"

# -----------------------------------------------------------------------------
# Status Labels
# -----------------------------------------------------------------------------
- name: "status: blocked"
  color: "d73a4a"
  description: "Blocked by external dependency"

- name: "status: in progress"
  color: "fbca04"
  description: "Currently being worked on"

- name: "status: needs review"
  color: "0075ca"
  description: "Ready for code review"

- name: "status: needs info"
  color: "cfd3d7"
  description: "More information required"

- name: "status: wontfix"
  color: "ffffff"
  description: "Will not be addressed"

- name: "status: duplicate"
  color: "cfd3d7"
  description: "Duplicate of another issue"

# -----------------------------------------------------------------------------
# Component Labels (Customise per project)
# -----------------------------------------------------------------------------
- name: "component: api"
  color: "c5def5"
  description: "API-related"

- name: "component: frontend"
  color: "c5def5"
  description: "Frontend-related"

- name: "component: database"
  color: "c5def5"
  description: "Database-related"

- name: "component: ci/cd"
  color: "c5def5"
  description: "CI/CD pipeline"

- name: "component: docker"
  color: "c5def5"
  description: "Docker configuration"

# -----------------------------------------------------------------------------
# Effort Labels
# -----------------------------------------------------------------------------
- name: "effort: small"
  color: "c2e0c6"
  description: "< 2 hours"

- name: "effort: medium"
  color: "fef2c0"
  description: "2-8 hours"

- name: "effort: large"
  color: "f9d0c4"
  description: "> 8 hours"

# -----------------------------------------------------------------------------
# Special Labels
# -----------------------------------------------------------------------------
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention needed"

- name: "ai: copilot"
  color: "5319e7"
  description: "Assigned to GitHub Copilot"

- name: "ai: claude"
  color: "d4a27f"
  description: "Assigned to Claude"
