"""
Email notification service for the REdI Trolley Audit System.

Sends notifications for:
1. Audit completion (to service line managers)
2. Issue creation (critical issues to MERT educators)
3. Issue assignment (to assigned person)
4. SLA breach warning (to assigned person and manager)
5. Issue escalation (to management chain)
6. Weekly random selection (to MERT educators)
"""
import logging
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string

logger = logging.getLogger(__name__)


class NotificationService:
    """Send email notifications for audit system events."""

    FROM_EMAIL = getattr(settings, 'DEFAULT_FROM_EMAIL', 'redi-noreply@health.qld.gov.au')

    def notify_audit_completed(self, audit):
        """Notify relevant parties that an audit has been completed."""
        subject = f'[REdI] Audit Completed: {audit.location.display_name}'
        context = {
            'audit': audit,
            'location': audit.location,
            'compliance': audit.overall_compliance,
        }
        message = (
            f"Audit completed for {audit.location.display_name}\n"
            f"Auditor: {audit.auditor_name}\n"
            f"Overall Compliance: {audit.overall_compliance}%\n"
            f"Date: {audit.completed_at}\n"
        )

        if audit.overall_compliance and audit.overall_compliance < 80:
            message += f"\nWARNING: Compliance below 80% threshold. Follow-up required.\n"

        recipients = self._get_service_line_contacts(audit.location.service_line)
        if recipients:
            self._send(subject, message, recipients)

    def notify_critical_issue(self, issue):
        """Notify MERT educators of a critical issue."""
        if issue.severity != 'Critical':
            return

        subject = f'[REdI] CRITICAL Issue: {issue.title}'
        message = (
            f"Critical issue reported at {issue.location.display_name}\n\n"
            f"Issue: {issue.issue_number} - {issue.title}\n"
            f"Category: {issue.issue_category}\n"
            f"Description: {issue.description}\n"
            f"Reported by: {issue.reported_by}\n"
            f"SLA Target: {issue.target_resolution_date}\n"
        )

        recipients = self._get_educator_emails()
        if recipients:
            self._send(subject, message, recipients)

    def notify_issue_assigned(self, issue):
        """Notify the assigned person about their new issue."""
        subject = f'[REdI] Issue Assigned: {issue.issue_number} - {issue.title}'
        message = (
            f"You have been assigned issue {issue.issue_number}\n\n"
            f"Location: {issue.location.display_name}\n"
            f"Severity: {issue.severity}\n"
            f"Description: {issue.description}\n"
            f"Target Resolution: {issue.target_resolution_date}\n"
        )

        # Try to find the assigned user's email
        from django.contrib.auth import get_user_model
        User = get_user_model()
        try:
            user = User.objects.get(username=issue.assigned_to)
            if user.email:
                self._send(subject, message, [user.email])
        except User.DoesNotExist:
            pass

    def notify_sla_warning(self, issue):
        """Send SLA breach warning."""
        subject = f'[REdI] SLA WARNING: {issue.issue_number} - {issue.title}'
        message = (
            f"SLA breach warning for issue {issue.issue_number}\n\n"
            f"Location: {issue.location.display_name}\n"
            f"Severity: {issue.severity}\n"
            f"Status: {issue.status}\n"
            f"Target Date: {issue.target_resolution_date}\n"
            f"Escalation Level: {issue.escalation_level}\n"
        )

        recipients = self._get_service_line_contacts(issue.location.service_line)
        recipients.extend(self._get_educator_emails())
        recipients = list(set(recipients))  # deduplicate

        if recipients:
            self._send(subject, message, recipients)

    def notify_weekly_selection(self, selection):
        """Notify educators about new weekly selection."""
        subject = f'[REdI] Weekly Random Selection: {selection.week_start_date} - {selection.week_end_date}'

        items = selection.items.select_related('location', 'location__service_line').order_by('selection_rank')
        trolley_list = '\n'.join([
            f"  {item.selection_rank}. {item.location.display_name} "
            f"({item.location.service_line.abbreviation}) - "
            f"Priority: {item.priority_score}"
            for item in items
        ])

        message = (
            f"Weekly random audit selection generated\n\n"
            f"Week: {selection.week_start_date} to {selection.week_end_date}\n"
            f"Generated by: {selection.generated_by}\n"
            f"Trolleys selected: {items.count()}\n\n"
            f"Selection:\n{trolley_list}\n"
        )

        recipients = self._get_educator_emails()
        if recipients:
            self._send(subject, message, recipients)

    def _get_service_line_contacts(self, service_line):
        """Get email addresses for a service line."""
        emails = []
        if service_line.contact_email:
            emails.append(service_line.contact_email)
        return emails

    def _get_educator_emails(self):
        """Get email addresses of all MERT educators."""
        from django.contrib.auth.models import Group
        try:
            group = Group.objects.get(name='MERT Educator')
            return list(group.user_set.filter(
                email__isnull=False
            ).exclude(email='').values_list('email', flat=True))
        except Group.DoesNotExist:
            return []

    def _send(self, subject, message, recipients):
        """Send an email with error handling."""
        try:
            send_mail(
                subject=subject,
                message=message,
                from_email=self.FROM_EMAIL,
                recipient_list=recipients,
                fail_silently=True,
            )
        except Exception as e:
            logger.error("Failed to send email notification: %s", e, exc_info=True)
